### ISSUE TITLE
JSONAPI broken now, at least on macOS

### ISSUE THREAD

**Issue by barracuda156** [RetroShare/libretroshare#149]
Initially got this error on my 10.6 powerpc, thought maybe it is something with a legacy OS support, but now the same on Sonoma arm64:
```
Looking for RsGxsCircles createGroup into class_rs_gxs_circles.xml calculated from refid: class_rs_gxs_circles_1a52419bf4682e64df4d5880390e931f53
Looking for RsGxsCircles DEFAULT_CIRCLE_BASE_URL into class_rs_gxs_circles.xml calculated from refid: class_rs_gxs_circles_1a4ba81728f153dd9b01989500d7580f5b
Looking for RsGxsCircles editCircle into class_rs_gxs_circles.xml calculated from refid: class_rs_gxs_circles_1ad35efcf69626c31e90872d80ebd4ccf4
Traceback (most recent call last):
  File "/opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_net_libretroshare/libretroshare/work/libretroshare-c54e0266e4483797c1d6bacee6f563979d683464/src/jsonapi//jsonapi-generator.py", line 377, in <module>
    processFile(os.path.join(doxPrefix, file))
  File "/opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_net_libretroshare/libretroshare/work/libretroshare-c54e0266e4483797c1d6bacee6f563979d683464/src/jsonapi//jsonapi-generator.py", line 193, in processFile
    tmpParam = paramsMap[tmpPN.text]
               ~~~~~~~~~^^^^^^^^^^^^
KeyError: 'circleId'
make[2]: *** [jsonapi-generator.workdir/src/jsonapi-includes.inl] Error 1
```

[build_log_sonoma.txt](https://github.com/user-attachments/files/16444779/build_log_sonoma.txt)

**Comment by barracuda156** [comment]
Any update on this?

**Comment by G10h4ck** [comment]
Thanks for reporting, I haven't had time to attempt to reproduce this, also because I don't have a macOS installation, the error appear to happen directly in the python code, which should behave _the same_ on all platforms, so it is a bit surprising. Could you post your python and doxygen versions please?
